#!/usr/bin/env bash
#
# Install ~/Applications/MECCHA CHAMELEON.app — one-click Dock launcher.
# Runs scripts/launch-meccha.sh (steam.exe -applaunch 4704690 -dx11).
#
# Usage: bash scripts/install-meccha-app.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=wine11-env.sh
source "$ROOT/scripts/wine11-env.sh"

APP_NAME="MECCHA CHAMELEON.app"
INSTALL_DIR="$INSTALL_APP_DIR"
APP_PATH="$INSTALL_DIR/$APP_NAME"
LOG_DIR="$ROOT/logs"

mkdir -p "$APP_PATH/Contents/MacOS" "$APP_PATH/Contents/Resources" "$LOG_DIR"

# App icon — prefer Steam's square logo.png, then library capsule art.
CACHE="$WINEPREFIX/drive_c/Program Files (x86)/Steam/appcache/librarycache/${APP_ID}"
ICON_SRC=""
for candidate in \
  "$CACHE"/*/logo.png \
  "$CACHE"/logo.png \
  "$CACHE"/*/library_capsule.jpg \
  "$CACHE"/*.jpg \
  "$CACHE"/*/*.jpg; do
  [[ -f "$candidate" ]] || continue
  ICON_SRC="$candidate"
  break
done

if [[ -n "$ICON_SRC" && -f "$ICON_SRC" ]]; then
  ICONSET="$(mktemp -d /tmp/meccha-icon.XXXXXX).iconset"
  mkdir -p "$ICONSET"
  sips -s format png "$ICON_SRC" --out "$ICONSET/source.png" >/dev/null
  # Crop to centered square (logo.png is often 16:9).
  w=$(sips -g pixelWidth  "$ICONSET/source.png" | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$ICONSET/source.png" | awk '/pixelHeight/{print $2}')
  side=$(( w < h ? w : h ))
  sips --cropToHeightWidth "$side" "$side" "$ICONSET/source.png" >/dev/null
  sips -z 1024 1024 "$ICONSET/source.png" --out "$ICONSET/source.png" >/dev/null
  sips -z 16 16     "$ICONSET/source.png" --out "$ICONSET/icon_16x16.png" >/dev/null
  sips -z 32 32     "$ICONSET/source.png" --out "$ICONSET/icon_16x16@2x.png" >/dev/null
  sips -z 32 32     "$ICONSET/source.png" --out "$ICONSET/icon_32x32.png" >/dev/null
  sips -z 64 64     "$ICONSET/source.png" --out "$ICONSET/icon_32x32@2x.png" >/dev/null
  sips -z 128 128   "$ICONSET/source.png" --out "$ICONSET/icon_128x128.png" >/dev/null
  sips -z 256 256   "$ICONSET/source.png" --out "$ICONSET/icon_128x128@2x.png" >/dev/null
  sips -z 256 256   "$ICONSET/source.png" --out "$ICONSET/icon_256x256.png" >/dev/null
  sips -z 512 512   "$ICONSET/source.png" --out "$ICONSET/icon_256x256@2x.png" >/dev/null
  sips -z 512 512   "$ICONSET/source.png" --out "$ICONSET/icon_512x512.png" >/dev/null
  sips -z 1024 1024 "$ICONSET/source.png" --out "$ICONSET/icon_512x512@2x.png" >/dev/null
  iconutil -c icns "$ICONSET" -o "$APP_PATH/Contents/Resources/AppIcon.icns"
  rm -rf "$ICONSET"
  echo "Icon source: $ICON_SRC"
fi

HAS_ICON=""
[[ -f "$APP_PATH/Contents/Resources/AppIcon.icns" ]] && HAS_ICON=1

cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIdentifier</key>
    <string>com.spdoub.meccha-chameleon</string>
    <key>CFBundleName</key>
    <string>MECCHA CHAMELEON</string>
    <key>CFBundleDisplayName</key>
    <string>MECCHA CHAMELEON</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSUIElement</key>
    <true/>
    <key>LSMultipleInstancesProhibited</key>
    <true/>
$( [[ -n "$HAS_ICON" ]] && printf '    <key>CFBundleIconFile</key>\n    <string>AppIcon</string>\n    <key>CFBundleIconName</key>\n    <string>AppIcon</string>\n' )
</dict>
</plist>
PLIST

USER_HOME="$HOME"

cat > "$APP_PATH/Contents/MacOS/launcher" <<LAUNCHER
#!/usr/bin/env bash
# Auto-generated by scripts/install-meccha-app.sh
# GUI apps get a minimal PATH — set everything explicitly.
export HOME="\${HOME:-$USER_HOME}"
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export LC_CTYPE="\${LC_CTYPE:-en_US.UTF-8}"

ROOT="$ROOT"
LOG="$LOG_DIR/meccha-launch.log"
mkdir -p "$LOG_DIR"

# Run in background so the .app returns immediately while launch continues.
(
  printf '\n== %s via MECCHA CHAMELEON.app ==\n' "\$(/bin/date '+%F %T')"
  export MECCHA_HUD="\${MECCHA_HUD:-0}"
  export MECCHA_FULLSCREEN="\${MECCHA_FULLSCREEN:-0}"
  /usr/bin/osascript -e 'display notification "Starting…" with title "MECCHA CHAMELEON"' 2>/dev/null || true
  /bin/bash "\$ROOT/scripts/launch-meccha.sh"
) >>"\$LOG" 2>&1 &
disown
exit 0
LAUNCHER

chmod +x "$APP_PATH/Contents/MacOS/launcher"

# Refresh Finder/Dock icon cache for the updated .icns
if [[ -f "$APP_PATH/Contents/Resources/AppIcon.icns" ]]; then
  touch "$APP_PATH"
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP_PATH" 2>/dev/null || true
fi

echo "Installed: $APP_PATH"
echo ""
if [[ "${1:-}" == "--pin-dock" ]] || [[ "${PIN_DOCK:-0}" == "1" ]]; then
  bash "$ROOT/scripts/add-meccha-to-dock.sh"
else
  echo "Pin to Dock: bash scripts/add-meccha-to-dock.sh"
fi
echo "Logs: $LOG_DIR/meccha-launch.log"
