#!/usr/bin/env bash
#
# Install ~/Applications/MECCHA CHAMELEON.app — one-click Dock launcher.
# Runs scripts/launch-meccha.sh (steam.exe -applaunch 4704690 -dx11).
#
# Usage: bash scripts/install-meccha-app.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="MECCHA CHAMELEON.app"
INSTALL_DIR="${INSTALL_APP_DIR:-$HOME/Applications}"
APP_PATH="$INSTALL_DIR/$APP_NAME"
LOG_DIR="$ROOT/logs"

mkdir -p "$APP_PATH/Contents/MacOS" "$LOG_DIR"

cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIdentifier</key>
    <string>com.spdoub.meccha-chameleon</string>
    <key>CFBundleName</key>
    <string>MECCHA CHAMELEON</string>
    <key>CFBundleDisplayName</key>
    <string>MECCHA CHAMELEON</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

cat > "$APP_PATH/Contents/MacOS/launcher" <<LAUNCHER
#!/usr/bin/env bash
# Auto-generated by scripts/install-meccha-app.sh
set -e
LOG="$LOG_DIR/meccha-launch.log"
mkdir -p "$LOG_DIR"
{
  printf '\n== %s via MECCHA CHAMELEON.app ==\n' "\$(date '+%F %T')"
  exec bash "$ROOT/scripts/launch-meccha.sh"
} >>"\$LOG" 2>&1
LAUNCHER

chmod +x "$APP_PATH/Contents/MacOS/launcher"

echo "Installed: $APP_PATH"
echo ""
echo "Drag 'MECCHA CHAMELEON' from ~/Applications onto your Dock."
echo "Requires the game installed in Steam (~/.wine-steam prefix)."
echo "Logs: $LOG_DIR/meccha-launch.log"
